import { Card } from '../../../cards/card/card.entity';
import { starterStraw } from '../utils/sets.cards';
import { character } from '../utils/types.cards';
import { red } from '../utils/colors.cards';
import { unlimited } from '../utils/status.cards';
import { alabasta } from '../utils/tags.cards';
import { common } from '../utils/rarities.cards';
import { slash } from '../utils/attributes.cards';

export const st1_009 = new Card();
st1_009.serial_number = 'ST01-009';
st1_009.fr_name = 'Nefertari Vivi';
st1_009.en_name = 'Nefertari Vivi';
st1_009.jp_name = 'ネフェタリ・ヴィヴィ';
st1_009.power = 4000;
st1_009.cost = 2;
st1_009.counter = 1000;
st1_009.set = starterStraw;
st1_009.type = character;
st1_009.colors = [red];
st1_009.tags = [alabasta];
st1_009.rarities = [common];
st1_009.status = unlimited;
st1_009.attribute = slash;
